site_name: Sabancı University SuperComputing Center
nav:
    - Quickstart: index.md
    - Tutorials:
        - Using Tosun Cluster: tosun-index.md
        - Using SunHPC Cluster: sunhpc-index.md
        - Scheduling with Slurm: slurm.md
        - Available Tools:
            - Matlab: 
                - General Information: matlab/matlab.md
                - Tutorial: pdf/matlab-tutorial.pdf
            - Materials Studio: ms.md
            - Comsol: comsol.md
            - Namd: namd.md
            - Tensorflow: tensorflow.md
    - FAQ: faq.md
    - Help: help.md
    - SU-HPC Kullanım Politikası: HPC_Kullanım_Politikası.md
    - Feragatname: Feragetname.md
theme: readthedocs
