site_name: Sabancı HPC Tutorials
nav:
    - Home: index.md
    - HPC Tools: hpc.md
    - Bioinformatics Tools: bio.md
    - Materials Science Tools: material.md
    - About: about.md
theme: readthedocs