site_name: Sabancı HPC Tutorials
nav:
    - Quickstart: index.md
    - Using SLURM: hpc.md
    - Bioinformatics Tools: bio.md
    - MatScience Tools: material.md
    - Engineering Tools: engineer.md
    - About: about.md
theme: readthedocs