site_name: Sabancı SuperComputing Center
nav:
    - Quickstart Tutorial: index.md
    - Using The Clusters:
        - Using Tosun Cluster: tosun/index.md
        - Using SunHPC Cluster: sunum/index.md
        - Scheduling with SLURM: tosun/slurm.md
        - Available Tools:
            - Bioinformatics: tosun/bio.md
            - Material Science: tosun/material.md
            - Machine Learning: tosun/learning.md
            - Data Science: tosun/data.md
    - Using SUNUM Cluster:
        - Quickstart: 
    - FAQ: faq.md
    - Help: help.md
    - SU-HPC Kullanım Politikası: docs/HPC_Kullanım_Politikası.md
    - Feragatname: docs/Feragetname.md
theme: readthedocs
